# Generated by Django 5.1.6 on 2025-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='datas',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datas',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='datas',
            name='mail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='datas',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
